[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.72"
cargo_metadata = "0.15.4"
cargo = "0.71.0"
chrono = { version = "0.4.26", default-features = false }
clap = "4.3.19"
clap_complete = "4.3.2"
conventional_commit_parser = "0.9.4"
crates-index = { version = "0.19.13", features = ["sparse-http"] }
dirs = "5.0.1"
dunce = "1.0.4"
expect-test = "1.4.1"
fake = "2.6.1"
git-cliff-core = { version = "1.2.0", default-features = false }
git-url-parse = "0.4.4"
http = "0.2"
ignore = "0.4.20"
lazy_static = "1.4.0"
once_cell = "1.18.0"
parse-changelog = { version = "0.6.1", default-features = false }
rayon = "1.7.0"
regex = "1.9.1"
reqwest = "0.11.18"
reqwest-middleware = "0.2.2"
reqwest-retry = "0.2.2"
secrecy = "0.8.0"
semver = "1.0.18"
serde = "1.0.175"
serde_json = "1.0.103"
strip-ansi-escapes = "0.1.1"
tempfile = "3.7.0"
tokio = "1.29.1"
toml = { version = "0.7.6" }
toml_edit = { version = "0.19.14" }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"
url = { version = "2.4.0", default-features = false }
walkdir = "2.3.3"
wiremock = "0.5.19"
