[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.72"
assert_cmd = "2.0.12"
async-trait = "0.1.73"
cargo_metadata = "0.17.0"
cargo = "0.72.2"
chrono = { version = "0.4.26", default-features = false }
clap = "4.3.21"
clap_complete = "4.3.2"
conventional_commit_parser = "0.9.4"
crates-index = { version = "2.1.0", features = ["git", "sparse"] }
dirs = "5.0.1"
dunce = "1.0.4"
expect-test = "1.4.1"
fake = "2.6.1"
git-cliff-core = { version = "1.2.0", default-features = false }
git-url-parse = "0.4.4"
http = "0.2"
ignore = "0.4.20"
lazy_static = "1.4.0"
once_cell = "1.18.0"
parse-changelog = { version = "0.6.2", default-features = false }
rayon = "1.7.0"
regex = "1.9.3"
reqwest = "0.11.18"
reqwest-middleware = "0.2.3"
reqwest-retry = "0.2.2"
secrecy = "0.8.0"
semver = "1.0.18"
serde = "1.0.183"
serde_json = "1.0.104"
strip-ansi-escapes = "0.2.0"
tempfile = "3.7.1"
tokio = "1.31.0"
toml = { version = "0.7.6" }
toml_edit = { version = "0.19.14" }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"
url = { version = "2.4.0", default-features = false }
walkdir = "2.3.3"
wiremock = "0.5.19"
