[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.66"
cargo_metadata = "0.15.1"
cargo-clone-core = "0.1.0"
cargo-edit = { version = "0.11.3", default-features = false }
chrono = { version = "0.4.22", default-features = false }
claim = "0.5.0"
clap = "4.0.20"
clap_complete = "4.0.5"
conventional_commit_parser = "0.9.4"
crates-index = "0.18.9"
dirs = "4.0.0"
dunce = "1.0.3"
expect-test = "1.4.0"
fake = "2.5.0"
fs_extra = "1.2.0"
git-cliff = { version = "0.8.1", default_features = false }
git-cliff-core = "0.8.1"
git-url-parse = "0.4.3"
octocrab = "0.17.0"
once_cell = "1.16.0"
secrecy = "0.8.0"
semver = "1.0.14"
serde_json = "1.0.87"
tempfile = "3.3.0"
tokio = "1.19.2"
toml_edit = "0.14.4"
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.15"
url = "2.3.0"
walkdir = "2.3.2"
wiremock = "0.5.15"
