[package]
name = "release-plz"
version = "0.2.19"
edition = "2021"
description = "Update version and changelog based on semantic versioning and conventional commits"
repository = "https://github.com/MarcoIeni/release-plz"
license = "MIT OR Apache-2.0"
readme = "../../README.md"
keywords = ["release", "please", "semver", "conventional", "commits"]
categories = ["command-line-utilities", "development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
release_plz_core = { path = "../release_plz_core", version = "0.2.18" }
git_cmd = { path = "../git_cmd", version = "0.1.7" }

anyhow = "1.0.58"
clap = { version = "3.2.6", features = ["derive", "env"] }
chrono = { version = "0.4.19", features = ["clock"], default-features = false }
secrecy = "0.8.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
tracing-log = "0.1.3"
url = "2.2.2"
dirs = "4.0.0"
git-cliff-core = "0.7.0"
git-url-parse = "0.4.2"
clap_complete = "3.2.2"
